### ISSUE TITLE
lv3 과제 관련 이슈

### ISSUE THREAD

**Issue by seongwop** [seongwop/post-comments#1]
1. 객체를 생성하는 데 있어서 builder 패턴을 알려주셨는데 과제에선 주로 dto나 entity 객체를 전달 받아서 값을 전달하는 식이라 인자가 대부분 객체 하나 뿐인데, 이런 경우에도 builder 패턴을 쓰는지 궁금합니다.

2. Service 쪽의 중복 함수를 util 패키지의 Validate 클래스에 전부 옮겼는데 이렇게 할 경우 Validate 클래스를 bean으로 등록하고 내부에서 repository 생성이라던지 불필요한 객체 생성이 일어나야하는데 그냥 같은 service 클래스 내 에서 중복 함수를 아래로 빼는 것이 더 나은 방법인지 궁금합니다. 또한, Validate 클래스의 다른 클래스에서 호출할 때 객체를 생성하고 호출하는 것과 상속을 받아서 호출하는 것 중 어떤 방법으로 써야할 지 궁금합니다. 

3. 커스텀 예외 클래스를 하나 만들어서 대부분의 예외 처리를 맡겼는데, 예외 클래스를 세부적으로 여러 개 만들어서 사용하는 것이 좋은 방향인지 궁금합니다.

4. 데이터의 반환을 전부 responseDto에 담아서 반환하느라 예외 메세지나 처리 메세지를 불가피하게 전부 StatusCode 라는 util 패키지의 enum 클래스에 담아서 사용했는데 좋지 않은 방법인지 궁금합니다.

**Comment by iamzin** [comment]
**1. Builder Pattern**
- 인자가 대부분 1개인 경우는 정확한 전제라고 보기 어려울 것 같습니다. 확장성과 유지보수성을 고려해보시면 좋을 것 같아요.

**2. Validate**
- 먼저 Util Class의 정의를 찾아보시면 좋을 것 같습니다.
- 활용 방법은 Validate 라는 클래스를 어떤 클래스로, 어떻게 만들었냐에 따라 다를 것 같네요. 일반적으로 해당 레이어에서만 사용되는 method라면 private 하게 가지고 있는게 나을 수도 있을 것 같습니다.

**3. Exception Handling**
- 말씀하신 Custom Exception Class를 어떻게 구현했는지 추가로 남겨주시면 좋을 것 같아요.

**4. Status Code**
- 좋지 않다고 생각한 이유가 있나요?
- 비즈니스 로직 전역에 Status Code 값이 삽입되어 있는 것보다 한 클래스 내에서 관리되는게 좋아 보입니다.
